### ISSUE TITLE
**ToolTip Text?**

### ISSUE THREAD

**Issue by JohnWilliamsArtist** [tilix/jw-artist#20]
in the gallery section i'd like additional information to appear when the mouse hovers over an image Ex. Blue Skies, Oil on Linen, 80cm x 60cm. 

 Is the first option to add tool tip text-style tags into the HTML or is there a better approach?

**Comment by JohnWilliamsArtist** [comment]
@drnw I raised an enhancement question (above) in issues - not sure if i had to tag you direct for you to get a notification?

**Comment by drnw** [comment]
Yes, you have to mention me so that I get the notification and subscription. Your website is built using Bootstrap, so you should checkout [Bootstrap Tooltips at  W3 Schools](http://www.w3schools.com/bootstrap/bootstrap_tooltip.asp)

**Comment by JohnWilliamsArtist** [comment]
cheers - will do...

John Williams
Scottish Contemporary Artist
