### ISSUE TITLE
Center Align Image in Intro Section

### ISSUE THREAD

**Issue by JohnWilliamsArtist** [tilix/jw-artist#30]
@drnw Ive tried at least six edits trying to get Intro Section image to align center.

Most recent wast to drop `style="align:center;"`into line 69 but still no joy.

Can yo give me a pointer? am I using wrong command? which element should I add it to?

J

**Comment by JohnWilliamsArtist** [comment]
@drnw Ive now edited line 70 `<div class="col-xs-6 text-center" style="align:center;">`

No Joy.

Im now wondering if <div class="col-xs-6> should have a float center command rather than float left?

j

**Comment by drnw** [comment]
Have you seen W3 School's [CSS Layout - Horizontal & Vertical Alignment](http://www.w3schools.com/css/css_align.asp) ?

To center an image, use `margin: auto;` and make it into a block element. For example:

`img {
    display: block;
    margin: auto;
    width: 40%;
}`

**Comment by drnw** [comment]
You'll also have to tweak the styling in the div containing the image.
![screen shot 2017-01-13 at 15 43 31](https://cloud.githubusercontent.com/assets/24733582/21935933/418231ce-d9a7-11e6-9119-4dbda0ed5c0f.png)

**Comment by JohnWilliamsArtist** [comment]
thanks for the support, I look forward to nailing this little pest.
