### ISSUE TITLE
Red Code

### ISSUE THREAD

**Issue by JohnWilliamsArtist** [tilix/jw-artist#35]
@drnw I wasnt able to follow your instructions to the letter :-( however in the process i managed to make the image do what I want.

But this has created some red code at line 74. Can you check this for me as I suspect it will cause issues later?
J

**Comment by drnw** [comment]
I could give you a fish or teach you to fish. I prefer the latter. Visit https://validator.w3.org and paste your page URL into the form there. Hint your page URL is https://tilix.github.io/jw-artist/

**Comment by JohnWilliamsArtist** [comment]
Rejoice; the penny dropped when I realised I was adding attributes to the img element
