### ISSUE TITLE
Tweak Nav Bar

### ISSUE THREAD

**Issue by JohnWilliamsArtist** [tilix/jw-artist#43]
@drnw   In the Nav Bar I'd like to make the following tweaks:- 

1. overall height 40px

2. John Williams font 14px

3. Button fonts 10px.

I added some style attributes to line 25 & 55 cause that seemed to work in Inspect Element but it hasnt changed anything.  I've passed it through validator but its not flagging anything.

Got any  hints foe me?? J.

**Comment by JohnWilliamsArtist** [comment]
@drnw  all hints are appreciated...

**Comment by drnw** [comment]
Patience is a virtue ....

On 16 Jan 2017, at 16:26, John Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


@drnw<https://github.com/drnw> all hints are appreciated...

-

**Comment by JohnWilliamsArtist** [comment]
Tomorrow never comes...

John Williams
Scottish Contemporary Artist

**Comment by drnw** [comment]
This is pretty basic stuff. You have:

`style="hieght40px; padding0px 0; font-size10px"`

Your code is very badly written. Try:

`style="height: 40px; padding: 0px 0; font-size: 10px"`

This may be better as it doesn't have any spelling mistakes and has better CSS syntax than your attempt.

**Comment by drnw** [comment]
Also try `style="font-size: 14px;"`
instead of `style="font-size14px;"`

**Comment by drnw** [comment]
One more thing, the HTML validator validates HTML not CSS. For CSS you should use the [CSS validator](http://www.css-validator.org). It would tell you:

Sorry! We found the following errors (5)
URI : https://tilix.github.io/jw-artist/
24		Parse Error hieght40px
24		Parse Error 0
24		Parse Error font-size10px
34		Parse Error font-size14px
125		Property opacity doesn't exist in CSS level 2.1 but exists in : 0.5 0.5

**Comment by JohnWilliamsArtist** [comment]
Thank You for the basic tips Bro x
