### ISSUE TITLE
Updated Site Launch

### ISSUE THREAD

**Issue by JohnWilliamsArtist** [tilix/jw-artist#45]
@drnw I'm happy for you to change the domain name setting so this becomes my home page.

**Comment by JohnWilliamsArtist** [comment]
@drnw Hey Bro, are you available to to change the domain name setting?

**Comment by drnw** [comment]
This weekend, if you play your cards right…N

On 19 Jan 2017, at 12:03, John Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


@drnw<https://github.com/drnw> Hey Bro, are you available to to change the domain name setting?

**Comment by JohnWilliamsArtist** [comment]
I will, cause I need some help to push this along x

**Comment by drnw** [comment]
Route 53 DNS reconfigured to point to Github Pages instead of AWS S3. Howzat?

**Comment by JohnWilliamsArtist** [comment]
Excellent! Much obliged 🥇 . The rubber has now hit the road and I'm on my way with my 2017 marketing campaign which will include blog posts :-O
